#
# SPDX-FileCopyrightText: Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: MIT-0
#
proc do_create_no_pins_pd_top {} {
	# create the system
	create_system no_pins_pd_top
	set_project_property BOARD {default}
	#set_project_property DEVICE {A5ED065BB32AE5SR0}
	#set_project_property DEVICE_FAMILY {Agilex 5}
	set_project_property HIDE_FROM_IP_CATALOG {false}
	set_use_testbench_naming_pattern 0 {}

	# add HDL parameters

	# add the components
	add_component config_clk_250m ip/no_pins_pd_top/config_clk_250m.ip altera_s10_configuration_clock config_clk_250m 19.1.4
	load_component config_clk_250m
	set_component_parameter_value CBX_AUTO_BLACKBOX {ALL}
	set_component_project_property HIDE_FROM_IP_CATALOG {false}
	save_component
	load_instantiation config_clk_250m
	remove_instantiation_interfaces_and_ports
	add_instantiation_interface clkout clock OUTPUT
	set_instantiation_interface_parameter_value clkout associatedDirectClock {}
	set_instantiation_interface_parameter_value clkout clockRate {0}
	set_instantiation_interface_parameter_value clkout clockRateKnown {false}
	set_instantiation_interface_parameter_value clkout externallyDriven {false}
	set_instantiation_interface_parameter_value clkout ptfSchematicName {}
	set_instantiation_interface_assignment_value clkout ui.blockdiagram.direction {OUTPUT}
	set_instantiation_interface_sysinfo_parameter_value clkout clock_rate {0}
	add_instantiation_interface_port clkout clkout clk 1 STD_LOGIC Output
	save_instantiation
	add_instance f2h_irq f2h_irq
	add_instance no_periph no_periph
	add_instance no_pins_hps no_pins_hps
	add_component usermode_entry ip/no_pins_pd_top/no_pins_pd_top_usermode_entry.ip intel_user_rst_clkgate usermode_entry 1.0.0
	load_component usermode_entry
	set_component_parameter_value outputType {Reset Interface}
	set_component_project_property HIDE_FROM_IP_CATALOG {false}
	save_component
	load_instantiation usermode_entry
	remove_instantiation_interfaces_and_ports
	add_instantiation_interface ninit_done reset OUTPUT
	set_instantiation_interface_parameter_value ninit_done associatedClock {}
	set_instantiation_interface_parameter_value ninit_done associatedDirectReset {}
	set_instantiation_interface_parameter_value ninit_done associatedResetSinks {none}
	set_instantiation_interface_parameter_value ninit_done synchronousEdges {NONE}
	add_instantiation_interface_port ninit_done ninit_done reset 1 STD_LOGIC Output
	save_instantiation

	# add wirelevel expressions

	# preserve ports for debug

	# add the connections
	add_connection config_clk_250m.clkout/no_periph.f2h_term_clock
	set_connection_parameter_value config_clk_250m.clkout/no_periph.f2h_term_clock clockDomainSysInfo {1}
	set_connection_parameter_value config_clk_250m.clkout/no_periph.f2h_term_clock clockRateSysInfo {}
	set_connection_parameter_value config_clk_250m.clkout/no_periph.f2h_term_clock clockResetSysInfo {}
	set_connection_parameter_value config_clk_250m.clkout/no_periph.f2h_term_clock resetDomainSysInfo {1}
	add_connection config_clk_250m.clkout/no_periph.f2sdram_term_clock
	set_connection_parameter_value config_clk_250m.clkout/no_periph.f2sdram_term_clock clockDomainSysInfo {1}
	set_connection_parameter_value config_clk_250m.clkout/no_periph.f2sdram_term_clock clockRateSysInfo {}
	set_connection_parameter_value config_clk_250m.clkout/no_periph.f2sdram_term_clock clockResetSysInfo {}
	set_connection_parameter_value config_clk_250m.clkout/no_periph.f2sdram_term_clock resetDomainSysInfo {1}
	add_connection config_clk_250m.clkout/no_pins_hps.agilex_5_soc_f2sdram_axi_clock
	set_connection_parameter_value config_clk_250m.clkout/no_pins_hps.agilex_5_soc_f2sdram_axi_clock clockDomainSysInfo {1}
	set_connection_parameter_value config_clk_250m.clkout/no_pins_hps.agilex_5_soc_f2sdram_axi_clock clockRateSysInfo {}
	set_connection_parameter_value config_clk_250m.clkout/no_pins_hps.agilex_5_soc_f2sdram_axi_clock clockResetSysInfo {}
	set_connection_parameter_value config_clk_250m.clkout/no_pins_hps.agilex_5_soc_f2sdram_axi_clock resetDomainSysInfo {1}
	add_connection config_clk_250m.clkout/no_pins_hps.agilex_5_soc_fpga2hps_clock
	set_connection_parameter_value config_clk_250m.clkout/no_pins_hps.agilex_5_soc_fpga2hps_clock clockDomainSysInfo {1}
	set_connection_parameter_value config_clk_250m.clkout/no_pins_hps.agilex_5_soc_fpga2hps_clock clockRateSysInfo {}
	set_connection_parameter_value config_clk_250m.clkout/no_pins_hps.agilex_5_soc_fpga2hps_clock clockResetSysInfo {}
	set_connection_parameter_value config_clk_250m.clkout/no_pins_hps.agilex_5_soc_fpga2hps_clock resetDomainSysInfo {1}
	add_connection no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps addressMapSysInfo {<address-map><slave name='no_pins_hps/agilex_5_soc.fpga2hps' start='0x0' end='0x100000000' datawidth='256' /></address-map>}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps addressWidthSysInfo {32}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps arbitrationPriority {1}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps baseAddress {0x0000}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps defaultConnection {0}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps domainAlias {}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.burstAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.clockCrossingAdapter {HANDSHAKE}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.enableAllPipelines {FALSE}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.enableEccProtection {FALSE}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.enableInstrumentation {FALSE}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.enableOutOfOrderSupport {FALSE}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.insertDefaultSlave {FALSE}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.interconnectResetSource {DEFAULT}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.interconnectType {STANDARD}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.maxAdditionalLatency {1}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.optimizeRdFifoSize {FALSE}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.piplineType {PIPELINE_STAGE}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.responseFifoType {REGISTER_BASED}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.syncResets {TRUE}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps qsys_mm.widthAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value no_periph.f2h_term_acelite_manager/no_pins_hps.agilex_5_soc_fpga2hps slaveDataWidthSysInfo {-1}
	add_connection no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram addressMapSysInfo {<address-map><slave name='no_pins_hps.agilex_5_soc.f2sdram' start='0x0' end='0x100000000' datawidth='256' /></address-map>}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram addressWidthSysInfo {32}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram arbitrationPriority {1}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram baseAddress {0x0000}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram defaultConnection {0}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram domainAlias {}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.burstAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.clockCrossingAdapter {HANDSHAKE}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.enableAllPipelines {FALSE}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.enableEccProtection {FALSE}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.enableInstrumentation {FALSE}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.enableOutOfOrderSupport {FALSE}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.insertDefaultSlave {FALSE}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.interconnectResetSource {DEFAULT}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.interconnectType {STANDARD}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.maxAdditionalLatency {1}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.optimizeRdFifoSize {FALSE}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.piplineType {PIPELINE_STAGE}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.responseFifoType {REGISTER_BASED}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.syncResets {TRUE}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram qsys_mm.widthAdapterImplementation {GENERIC_CONVERTER}
	set_connection_parameter_value no_periph.f2sdram_term_axi4_man/no_pins_hps.agilex_5_soc_f2sdram slaveDataWidthSysInfo {-1}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_0
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_0 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_0 irqNumber {0}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_1
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_1 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_1 irqNumber {1}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_10
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_10 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_10 irqNumber {10}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_11
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_11 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_11 irqNumber {11}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_12
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_12 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_12 irqNumber {12}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_13
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_13 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_13 irqNumber {13}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_14
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_14 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_14 irqNumber {14}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_15
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_15 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_15 irqNumber {15}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_16
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_16 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_16 irqNumber {16}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_17
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_17 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_17 irqNumber {17}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_18
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_18 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_18 irqNumber {18}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_19
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_19 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_19 irqNumber {19}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_2
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_2 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_2 irqNumber {2}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_20
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_20 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_20 irqNumber {20}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_21
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_21 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_21 irqNumber {21}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_22
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_22 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_22 irqNumber {22}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_23
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_23 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_23 irqNumber {23}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_24
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_24 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_24 irqNumber {24}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_25
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_25 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_25 irqNumber {25}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_26
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_26 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_26 irqNumber {26}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_27
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_27 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_27 irqNumber {27}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_28
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_28 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_28 irqNumber {28}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_29
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_29 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_29 irqNumber {29}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_3
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_3 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_3 irqNumber {3}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_30
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_30 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_30 irqNumber {30}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_31
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_31 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_31 irqNumber {31}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_32
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_32 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_32 irqNumber {32}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_33
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_33 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_33 irqNumber {33}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_34
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_34 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_34 irqNumber {34}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_35
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_35 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_35 irqNumber {35}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_36
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_36 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_36 irqNumber {36}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_37
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_37 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_37 irqNumber {37}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_38
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_38 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_38 irqNumber {38}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_39
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_39 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_39 irqNumber {39}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_4
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_4 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_4 irqNumber {4}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_40
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_40 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_40 irqNumber {40}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_41
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_41 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_41 irqNumber {41}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_42
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_42 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_42 irqNumber {42}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_43
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_43 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_43 irqNumber {43}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_44
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_44 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_44 irqNumber {44}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_45
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_45 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_45 irqNumber {45}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_46
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_46 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_46 irqNumber {46}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_47
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_47 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_47 irqNumber {47}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_48
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_48 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_48 irqNumber {48}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_49
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_49 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_49 irqNumber {49}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_5
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_5 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_5 irqNumber {5}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_50
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_50 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_50 irqNumber {50}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_51
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_51 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_51 irqNumber {51}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_52
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_52 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_52 irqNumber {52}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_53
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_53 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_53 irqNumber {53}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_54
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_54 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_54 irqNumber {54}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_55
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_55 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_55 irqNumber {55}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_56
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_56 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_56 irqNumber {56}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_57
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_57 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_57 irqNumber {57}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_58
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_58 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_58 irqNumber {58}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_59
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_59 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_59 irqNumber {59}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_6
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_6 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_6 irqNumber {6}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_60
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_60 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_60 irqNumber {60}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_61
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_61 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_61 irqNumber {61}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_62
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_62 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_62 irqNumber {62}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_63
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_63 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_63 irqNumber {63}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_7
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_7 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_7 irqNumber {7}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_8
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_8 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_8 irqNumber {8}
	add_connection no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_9
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_9 interruptsUsedSysInfo {18446744073709551615}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_fpga2hps_interrupt/f2h_irq.gp_out_irq_f2h_irq_9 irqNumber {9}
	add_connection no_pins_hps.agilex_5_soc_hps_gp/f2h_irq.hps_gp_split_hps_gp
	set_connection_parameter_value no_pins_hps.agilex_5_soc_hps_gp/f2h_irq.hps_gp_split_hps_gp endPort {}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_hps_gp/f2h_irq.hps_gp_split_hps_gp endPortLSB {0}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_hps_gp/f2h_irq.hps_gp_split_hps_gp startPort {}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_hps_gp/f2h_irq.hps_gp_split_hps_gp startPortLSB {0}
	set_connection_parameter_value no_pins_hps.agilex_5_soc_hps_gp/f2h_irq.hps_gp_split_hps_gp width {0}
	add_connection usermode_entry.ninit_done/no_periph.f2h_term_reset
	set_connection_parameter_value usermode_entry.ninit_done/no_periph.f2h_term_reset clockDomainSysInfo {16}
	set_connection_parameter_value usermode_entry.ninit_done/no_periph.f2h_term_reset clockResetSysInfo {}
	set_connection_parameter_value usermode_entry.ninit_done/no_periph.f2h_term_reset resetDomainSysInfo {16}
	add_connection usermode_entry.ninit_done/no_periph.f2sdram_term_reset
	set_connection_parameter_value usermode_entry.ninit_done/no_periph.f2sdram_term_reset clockDomainSysInfo {16}
	set_connection_parameter_value usermode_entry.ninit_done/no_periph.f2sdram_term_reset clockResetSysInfo {}
	set_connection_parameter_value usermode_entry.ninit_done/no_periph.f2sdram_term_reset resetDomainSysInfo {16}
	add_connection usermode_entry.ninit_done/no_pins_hps.agilex_5_soc_f2sdram_axi_reset
	set_connection_parameter_value usermode_entry.ninit_done/no_pins_hps.agilex_5_soc_f2sdram_axi_reset clockDomainSysInfo {16}
	set_connection_parameter_value usermode_entry.ninit_done/no_pins_hps.agilex_5_soc_f2sdram_axi_reset clockResetSysInfo {}
	set_connection_parameter_value usermode_entry.ninit_done/no_pins_hps.agilex_5_soc_f2sdram_axi_reset resetDomainSysInfo {16}
	add_connection usermode_entry.ninit_done/no_pins_hps.agilex_5_soc_fpga2hps_reset
	set_connection_parameter_value usermode_entry.ninit_done/no_pins_hps.agilex_5_soc_fpga2hps_reset clockDomainSysInfo {16}
	set_connection_parameter_value usermode_entry.ninit_done/no_pins_hps.agilex_5_soc_fpga2hps_reset clockResetSysInfo {}
	set_connection_parameter_value usermode_entry.ninit_done/no_pins_hps.agilex_5_soc_fpga2hps_reset resetDomainSysInfo {16}

	# add the exports
	set_interface_property h2f_reset EXPORT_OF no_pins_hps.agilex_5_soc_h2f_reset
	set_interface_property hps2fpga_axi_clock EXPORT_OF no_pins_hps.agilex_5_soc_hps2fpga_axi_clock
	set_interface_property hps2fpga_axi_reset EXPORT_OF no_pins_hps.agilex_5_soc_hps2fpga_axi_reset
	set_interface_property hps2fpga EXPORT_OF no_pins_hps.agilex_5_soc_hps2fpga
	set_interface_property lwhps2fpga_axi_clock EXPORT_OF no_pins_hps.agilex_5_soc_lwhps2fpga_axi_clock
	set_interface_property lwhps2fpga_axi_reset EXPORT_OF no_pins_hps.agilex_5_soc_lwhps2fpga_axi_reset
	set_interface_property lwhps2fpga EXPORT_OF no_pins_hps.agilex_5_soc_lwhps2fpga
	set_interface_property emac_ptp_clk EXPORT_OF no_pins_hps.agilex_5_soc_emac_ptp_clk
	set_interface_property emac_timestamp_clk EXPORT_OF no_pins_hps.agilex_5_soc_emac_timestamp_clk
	set_interface_property emac_timestamp_data EXPORT_OF no_pins_hps.agilex_5_soc_emac_timestamp_data
	set_interface_property emac0_app_rst EXPORT_OF no_pins_hps.agilex_5_soc_emac0_app_rst
	set_interface_property emac0 EXPORT_OF no_pins_hps.agilex_5_soc_emac0
	set_interface_property spim0 EXPORT_OF no_pins_hps.agilex_5_soc_spim0
	set_interface_property spim0_sclk_out EXPORT_OF no_pins_hps.agilex_5_soc_spim0_sclk_out
	set_interface_property uart1 EXPORT_OF no_pins_hps.agilex_5_soc_uart1
	set_interface_property i2c0_scl_i EXPORT_OF no_pins_hps.agilex_5_soc_I2C0_scl_i
	set_interface_property i2c0_scl_oe EXPORT_OF no_pins_hps.agilex_5_soc_I2C0_scl_oe
	set_interface_property i2c0 EXPORT_OF no_pins_hps.agilex_5_soc_I2C0
	set_interface_property h2f_user0_clk EXPORT_OF no_pins_hps.agilex_5_soc_h2f_user0_clk
	set_interface_property h2f_user1_clk EXPORT_OF no_pins_hps.agilex_5_soc_h2f_user1_clk
	set_interface_property hps_io EXPORT_OF no_pins_hps.agilex_5_soc_hps_io
	set_interface_property emif_bank3a_hps_emif_mem_0 EXPORT_OF no_pins_hps.emif_bank3a_hps_emif_mem_0
	set_interface_property emif_bank3a_hps_emif_oct_0 EXPORT_OF no_pins_hps.emif_bank3a_hps_emif_oct_0
	set_interface_property emif_bank3a_hps_emif_ref_clk_0 EXPORT_OF no_pins_hps.emif_bank3a_hps_emif_ref_clk_0

	# set values for exposed HDL parameters
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.burstAdapterImplementation GENERIC_CONVERTER
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.clockCrossingAdapter HANDSHAKE
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.enableAllPipelines FALSE
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.enableEccProtection FALSE
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.enableInstrumentation FALSE
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.enableOutOfOrderSupport FALSE
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.insertDefaultSlave FALSE
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.interconnectResetSource DEFAULT
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.interconnectType STANDARD
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.maxAdditionalLatency 1
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.optimizeRdFifoSize FALSE
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.piplineType PIPELINE_STAGE
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.responseFifoType REGISTER_BASED
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.syncResets TRUE
	set_domain_assignment no_periph.f2h_term_acelite_manager qsys_mm.widthAdapterImplementation GENERIC_CONVERTER
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.burstAdapterImplementation GENERIC_CONVERTER
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.clockCrossingAdapter HANDSHAKE
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.enableAllPipelines FALSE
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.enableEccProtection FALSE
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.enableInstrumentation FALSE
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.enableOutOfOrderSupport FALSE
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.insertDefaultSlave FALSE
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.interconnectResetSource DEFAULT
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.interconnectType STANDARD
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.maxAdditionalLatency 1
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.optimizeRdFifoSize FALSE
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.piplineType PIPELINE_STAGE
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.responseFifoType REGISTER_BASED
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.syncResets TRUE
	set_domain_assignment no_periph.f2sdram_term_axi4_man qsys_mm.widthAdapterImplementation GENERIC_CONVERTER

	# set the the module properties
	set_module_property BONUS_DATA {<?xml version="1.0" encoding="UTF-8"?>
<bonusData>
 <element __value="config_clk_250m">
  <datum __value="_sortIndex" value="0" type="int" />
 </element>
 <element __value="f2h_irq">
  <datum __value="_sortIndex" value="4" type="int" />
 </element>
 <element __value="no_periph">
  <datum __value="_sortIndex" value="3" type="int" />
 </element>
 <element __value="no_pins_hps">
  <datum __value="_sortIndex" value="2" type="int" />
 </element>
 <element __value="onchip_M20Kx64.axi_s1">
  <datum __value="baseAddress" value="65536" type="String" />
 </element>
 <element __value="usermode_entry">
  <datum __value="_sortIndex" value="1" type="int" />
 </element>
</bonusData>
}
	set_module_property FILE {no_pins_pd_top.qsys}
	set_module_property GENERATION_ID {0x00000000}
	set_module_property NAME {no_pins_pd_top}

	# save the system
	sync_sysinfo_parameters
	save_system no_pins_pd_top
}
